### ISSUE TITLE
[FEATURE REQUEST] Docker Support

### ISSUE THREAD

**Issue by movchan74** [mobiusml/aana_sdk#147]
### Feature Summary

Add Docker support for Aana apps.

### Justification/Rationale

We have [Dockerfile](https://github.com/mobiusml/aana_sdk/blob/0e4d62a92419ebe187b4358b317cb636962d4fac/Dockerfile) in the Aana SDK repo but it was created for the apps in the projects directory. 

We should create a Dockerfile or docker-compose file for the apps created with [app template](https://github.com/mobiusml/aana_app_template).

### Proposed Implementation
1. Create a docker-compose.yml file for Aana apps:
   - Include service definitions for the app and PostgreSQL database
   - Configure appropriate environment variables and volume mappings

3. Implement Docker support in the [summarize video app](https://github.com/mobiusml/aana_summarize_video) as a test case:
   - Add Dockerfile/docker-compose.yml
   - Test it

4. Add Docker support to the [Aana app template](https://github.com/mobiusml/aana_app_template):
   - Include Dockerfile and docker-compose.yml in the template
   - Update template documentation to reflect Docker usage

5. Update documentation:
   - Add Docker-related instructions to the README files of app repos and the app template repo
   - Update the [Aana SDK docs](https://mobiusml.github.io/aana_sdk/pages/docker/)

### Tasks
- [x] Create a docker-compose.yml file for Aana apps
- [x] Implement Docker support in the [summarize video app](https://github.com/mobiusml/aana_summarize_video)
- [ ] Add Docker support to the [Aana app template](https://github.com/mobiusml/aana_app_template)
- [ ] Update README files with Docker instructions (app repos and app template repo)
- [ ] Update Aana SDK documentation with [Docker instructions](https://mobiusml.github.io/aana_sdk/pages/docker/)

### Dockerfile vs docker-compose
Since we have a database it might be better to use docker-compose and add PostgreSQL container to the docker-compose file. That would be more realistic to the production environment and my recommendation is to use docker-compose.
